version: "3.8"

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/vescaffr/data/wp
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/vescaffr/data/db
                        o: bind
                        type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    image: nginx:42
    build: ./requirements/nginx/.
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  wordpress:
    container_name: wordpress
    image: wordpress:42
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
  mariadb:
    container_name: mariadb
    image: mariadb:42
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

